### ISSUE TITLE
DNS Record serializer/deserializer null reference

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/ss_issue_tracker#3]
Occasionally happens on new installs. Suspected that this also leads to pushing junk serialized data to the DNS Record store which leads to inconsistent host resolution (probably forcing multiple forward request) Trace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: jsonSerializer
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at ca.safesurfing.serialization.DnsRecordConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)```
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at ssmdns.ca.safesurfing.dns.DnsCache.PushRecordToDatabase(DnsMessage msg, String hostName, RecordType recordType)
   at ssmdns.ca.safesurfing.dns.DnsCache.Lookup(String hostName, RecordType recordType)
   at ssmdns.ca.safesurfing.dns.DnsCache.LoadLocalDnsCache()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by TechnikEmpire** [comment]
Appears fixed by extra null checking in DnsCache::PushToDatabase(...) as serializing in this method was the trigger of the null reference exception in Newtonson.Json
